name: 'coverage'
on:
    push:
        branches:
            - master
            - main
    pull_request:
        branches:
            - master
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
          - name: Get Cover 
            uses: orgoro/coverage@v3.2
            with:
                coverageFile: python-final-diplom/reference/netology_pd_diplom/.coverage.xml
                token: ${{ secrets.GITHUB_TOKEN }}
