# name: 'coverage'
# on:
#     push:
#         branches:
#             - master
#             - main
#     pull_request:
#         branches:
#             - master
#             - main
# jobs:
#     coverage:
#         runs-on: ubuntu-latest
#         steps:
#           - name: Get Cover 
#             uses: orgoro/coverage@v3.2
#             with:
#                 coverageFile: python-final-diplom/reference/netology_pd_diplom/.coverage.xml
#                 token: ${{ secrets.GITHUB_TOKEN }}

name: 'Test and Coverage Report'

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest coverage
      - name: Run tests with coverage
        run: |
          pytest --cov=. --cov-report xml:cov.xml
      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittest
