# name: 'coverage'
# on:
#     push:
#         branches:
#             - master
#             - main
#     pull_request:
#         branches:
#             - master
#             - main
# jobs:
#     coverage:
#         runs-on: ubuntu-latest
#         steps:
#           - name: Get Cover 
#             uses: orgoro/coverage@v3.2
#             with:
#                 coverageFile: python-final-diplom/reference/netology_pd_diplom/.coverage.xml
#                 token: ${{ secrets.GITHUB_TOKEN }}

name: 'Тестирование и покрытие кода'

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория с подмодулями
      - name: Клонирование репозитория
        uses: actions/checkout@v3
        with:
          submodules: true

      # Шаг 2: Установка Python 3.10
      - name: Установка Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      # Шаг 3: Установка зависимостей
      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov coverage

      # Шаг 4: Проверка структуры (диагностика)
      - name: Проверка структуры проекта
        run: |
          echo "Содержимое корня:"
          ls -l
          echo "Папка python-final-diplom/reference/netology_pd_diplom:"
          ls -l python-final-diplom/reference/netology_pd_diplom || echo "Директория не найдена"
          echo "Папка с тестами:"
          ls -l python-final-diplom/reference/netology_pd_diplom/tests || echo "Папка с тестами не найдена"

      # Шаг 5: Запуск тестов с покрытием
      - name: Запуск тестов с покрытием
        run: |
          export DJANGO_SETTINGS_MODULE=reference.netology_pd_diplom.netology_pd_diplom.settings
          pytest python-final-diplom/reference/netology_pd_diplom/tests/ --cov=netology_pd_diplom --cov-report=xml:coverage.xml
        env:
          PYTHONPATH: ${{ github.workspace }}/python-final-diplom/reference/netology_pd_diplom
          DJANGO_SETTINGS_MODULE: reference.netology_pd_diplom.netology_pd_diplom.settings

      # Шаг 6: Отправка отчета покрытия в Codecov
      - name: Отправка отчета покрытия
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: unittests
          fail_ci_if_error: true

