# name: 'coverage'
# on:
#     push:
#         branches:
#             - master
#             - main
#     pull_request:
#         branches:
#             - master
#             - main
# jobs:
#     coverage:
#         runs-on: ubuntu-latest
#         steps:
#           - name: Get Cover 
#             uses: orgoro/coverage@v3.2
#             with:
#                 coverageFile: python-final-diplom/reference/netology_pd_diplom/.coverage.xml
#                 token: ${{ secrets.GITHUB_TOKEN }}

name: 'Тестирование и покрытие кода'

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Установка Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest coverage pytest-cov

      - name: Запуск тестов с покрытием
        run: |
          export DJANGO_SETTINGS_MODULE=reference.netology_pd_diplom.settings
          cd python-final-diplom/reference
          pytest --cov=netology_pd_diplom --cov-report xml:coverage.xml
        env:
          PYTHONPATH: ${{ github.workspace }}  # Автоматически добавляется корневой каталог
          DJANGO_SETTINGS_MODULE: reference.netology_pd_diplom.settings

      - name: Загрузка отчета покрытия
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittest


