# name: 'coverage'
# on:
#     push:
#         branches:
#             - master
#             - main
#     pull_request:
#         branches:
#             - master
#             - main
# jobs:
#     coverage:
#         runs-on: ubuntu-latest
#         steps:
#           - name: Get Cover 
#             uses: orgoro/coverage@v3.2
#             with:
#                 coverageFile: python-final-diplom/reference/netology_pd_diplom/.coverage.xml
#                 token: ${{ secrets.GITHUB_TOKEN }}

name: 'Тестирование и покрытие кода'


on:
  push:
    branches:
      - master
      - main
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      # Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v3


      # Установка Python 3.10
      - name: Setup Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'


      # Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov coverage


      # Отладка структуры каталогов (по желанию)
      - name: Show project directory structure
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          ls -la python-final-diplom
          ls -la python-final-diplom/reference


      # Запуск тестов с покрытием
      - name: Run tests with coverage
        run: |
          export DJANGO_SETTINGS_MODULE=reference.netology_pd_diplom.netology_pd_diplom.settings
          cd python-final-diplom/reference
          pytest --cov=netology_pd_diplom --cov-report=xml:coverage.xml tests/
        env:
          PYTHONPATH: ${{ github.workspace }}/python-final-diplom/reference
          DJANGO_SETTINGS_MODULE: reference.netology_pd_diplom.netology_pd_diplom.settings


      # Отправка отчёта покрытия в Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: unittests
          fail_ci_if_error: true


